# repo-sync.yaml
apiVersion: configsync.gke.io/v1alpha1
kind: RepoSync
metadata:
  name: repo-sync
  namespace: hello-d-001
spec:
  git:
    repo: https://github.com/renukasathish/anthos-config-management
    revision: HEAD
    branch: main
    dir: "hello-namespace/config-root"
    auth: none
