apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: hello-d-001
  annotations:
    configmanagement.gke.io/cluster-selector: selector-central-or-west
  labels:
    name: mypod
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
