apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    configmanagement.gke.io/cluster-selector: dev
  labels:
    name: mypod
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
