apiVersion: v1
data:
  username: anthos-test
  password: anthos-pass-secret
kind: Secret
metadata:
  name: mysecret
  namespace: "hello-d-001"
  resourceVersion: "164619"
  uid: cfee02d6-c137-11e5-8d73-42010af00002
type: Opaque
